### ISSUE TITLE
Roadmap to MVP

### ISSUE THREAD

**Issue by coolaj86** [dashhive/DashJoin.js#18]
- [x] get masternode list https://github.com/dashpay/dashd-rpc/issues/68
- [x] select masternode
- [x] write a full wallet implementation from scratch, y'know... using DashHD that is
- [x] generate lots of Dash to the testnet addresses
- [x] connect to masternode and send Hello (`version` + `verack`)
- [x] send `pong`
- [x] send `senddsq`
- [x] create collateral transaction (network fee is collateral, output addr is change addr)
- [x] handshake with `dsa` + collateral
- [x] receive `dssu` and `dsq`
- [x] receive `dsf` 
- [x] send `dss`
- [x] figure out why `dss` signature isn't valid
- [x] finish updating dashtx https://github.com/dashhive/DashTx.js/pull/64 so that it can run without local modifications
