### ISSUE TITLE
Todo for Monday

### ISSUE THREAD

**Issue by coolaj86** [dashhive/DashJoin.js#23]
- [x] lookup txids using `dash-cli` to know for sure whether LE or BE is correct when parsing
- [x] sign with `sighash_all` using the older DashTx code \
   (update to not throw when missing keys)
   (could use a triple check)
- [x] ~~create tx (again) with `dash-cli` and the given keys~~ \
   (can't be done due to lacking features)
- [x] write dss verifier (one that checks input signatures)
- [x] ~~check that a bad signature on collateral returns an error~~ \
   (the problem was the extra size byte when using `pubKeyHash` to construct `script`)
